[build]
  publish = "."

[context.production.environment]
  SKIP_FRAMEWORK_DETECTION = "true"

[[redirects]]
  from = "/api/*"
  to = "https://khadock-backend.onrender.com/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"